apiVersion: v1
kind: ConfigMap
metadata:
  name: msgapp-backend-config
  labels:
    app: msgapp
    component: backend
data:
  MONGO_URL: "mongodb://msgapp-mongodb:27017/{{ .Values.mongodb.database }}"
  PORT: "{{ .Values.backend.service.port }}"
  JWT_SECRET: "{{ .Values.backend.env.jwtSecret }}"
